refactor : 배포를 위한 yml 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,3 +84,18 @@ jobs:
               "$JAR_NAME" > app.log 2>&1 & disown
               
             echo "Deployment script executed for $JAR_NAME"
+
+            echo "Waiting for application to start on port $APP_PORT..."
+            timeout=60 # 대기 시간 (60초)
+            while ! nc -z localhost $APP_PORT && [ $timeout -gt 0 ]; do
+              echo "Application not yet available. Waiting..."
+              sleep 5
+              timeout=$((timeout-5))
+            done
+            
+            if [ $timeout -le 0 ]; then
+              echo "Error: Application failed to start within the timeout period."
+              exit 1 # 오류 발생 시 GitHub Actions 실패
+            else
+              echo "Application is up and running!"
+            fi
